version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0.4
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
          org_slug: gh/jenny-miggin
          pre-steps:
            steps:
              run: log in to CircleCI
              command: |
                circleci setup --no-prompt --token "${CIRCLECI_API_TOKEN}"
          context: cci
      - shellcheck/check:
          filters: *filters
      - orb-tools/publish:
          orb_name: jmi-space/my-orb-2
          vcs_type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          orb_name: jmi-space/my-orb-2
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters

# VS Code Extension Version: 1.3.0