description: >
  This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here.
  If you do not require an executor, you can simply delete this directory.
docker:
  - image: 'cimg/node:<<parameters.tag>>'
parameters:
  tag:
    default: lts
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
  resource_class:
        default: large
        description: Configure the executor resource class
        enum:
        - small
        - medium
        - medium+
        - large
        - xlarge
        - 2xlarge
        - 2xlarge+
        type: enum
